{% set name = "Ipopt" %}
{% set version = "3.13.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: Ipopt
    url: https://github.com/coin-or/Ipopt/archive/releases/{{ version }}.tar.gz
    sha256: 86354b36c691e6cd6b8049218519923ab0ce8a6f0a432c2c0de605191f2d4a1c
    patches:
      - linux-configure.patch  # [linux]

  - folder: Mumps
    url: https://github.com/coin-or-tools/ThirdParty-Mumps/archive/releases/1.6.2.tar.gz
    sha256: 0cfdd30b9cb42d9539ad9c495629f56dd1fc0b59cea691bbe71a129fabd8895d
    patches:
      - thirdparty-mumps-linux-configure.patch  # [linux]

build:
  skip: true  # [win]
  number: 1
  run_exports:
    - {{ pin_subpackage('ipopt', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - wget
    - pkgconfig
  host:
    - libblas
    - liblapack
    - metis
    - ampl-mp
  run:
    - ampl-mp

test:
  files:
    - test
    - mytoy.nl

  requires:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

about:
  home: https://projects.coin-or.org/Ipopt/
  license: EPL-1.0
  license_file: Ipopt/LICENSE
  summary: Software package for large-scale nonlinear optimization

extra:
  recipe-maintainers:
    - pstjohn
    - bluescarni
    - jschueller
