travis:
  secure:
    BINSTAR_TOKEN: kd6omx1XJy1PCDcUYzzV/uDgFMMobfTa80YE5fAzfZMG/8yWjPRSwsbPalZbIgw/2v4BPOR6fA7qOfV/1qcLYyWxeM4Mm1KEMmKr99YUwX32ERuu4D/x7eWgLGfi/ro7lUT5ouXRlehRdXMzfn7K9Z9gmv3krXoBF9VeU7qdoz0btb/CMOihUpyl1a6Yyk2CSdGW6N0VmSQAJC+7JvF1AKbl72T7cx10JRL3RosxvGDan5EVuKDNrCnMYZPMW/eesuVh5jaXIr19oykBMhI8IwUwexJApwQdDE/3extvQbV+3XMUKWs4CVTOJnAlbOLGNURPhI4dDaoDgddLfU92hnfkWMwHqbSzK2JCgC6bhwuWMzWf76M9piRAav8yMUTYsvOa9Vzlzm3+s1G0WiU3Y5Jvks/dntnhxJ5kS/JBHsOuRwZZ53VdkiQA+7IecsH52t3itT3twbV2sAQy10YTox9HxMyauE8FMEVJ9uhsnNYOBgtIDgE5pbkakplHVHuK8O/74dmRbW/ilncgqCMEhV8XJQZpwK84JTiB47I+xnBZdSuwDUkTsE+7Ry6nIwF1Gxkk3oU9zQvVp0eT0C293QB5kP7kHkkRf6qrTF2q0QoMoKQrNfF2sqhXdWDXGdNpG34MzYnteIJN4QcNzQMWQUu9BQ/4kvYr0W1vNX1RCqM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
